apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-recovery.fullname" . }}-app-config
  labels:
{{ include "service-recovery.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-recovery-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-recovery-dev01
    db_pass: DXkgcPUoLemkW6U
    db_name: service-recovery-dev01
    rabbit_host: dove.rmq.cloudamqp.com
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
    service_wallet_host: http://service-wallet-dev01:37007
    service_auth_host: http://service-recovery-dev01:37001
