apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-notification.fullname" . }}-app-config
  labels:
{{ include "service-notification.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-notification-dev01.yaml: |
    app_host_url: http://zipzero.com
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-notification-dev01
    db_pass: yb2zDGweLhzcTei
    db_name: service-notification-dev01
    rabbit_host: dove.rmq.cloudamqp.com
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
