version: 2.1
executors:
  toolkit:
    docker:
      - image: eu.gcr.io/development-gg/toolkit:1.2.3

jobs:
  build:
    executor: toolkit
    steps:
      - setup_remote_docker
      - checkout
      - run: echo ${GOOGLE_AUTH} > gcp-key.json
      - run: gcloud auth activate-service-account --key-file gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud auth configure-docker
      - run: gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --region ${COMPUTE_REGION}
      - run: helm repo add zipzero gs://zipzero
      - run: helm repo update
      - run: ./scripts/helm-bild-release.sh
