apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: {{ template "service-auth.fullname" . }}
  labels:
{{ include "service-auth.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ default "1" .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "service-auth.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "service-auth.fullname" . }}
          resources:
            limits:
              memory: {{ index .Values.resources.limits.mem .Values.envtype | default .Values.resources.limits.mem._default }}
              cpu: {{ index .Values.resources.limits.cpu .Values.envtype | default .Values.resources.limits.cpu._default }}
            requests:
              memory: {{ index .Values.resources.requests.mem .Values.envtype | default .Values.resources.requests.mem._default }}
              cpu: {{ index .Values.resources.requests.cpu .Values.envtype | default .Values.resources.requests.cpu._default }}
          image: {{ .Values.image.repo }}{{ .Values.image.path }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: service-auth-dev01-app-config
              subPath: service-auth-dev01.yaml
          ports:
            - containerPort: {{ .Values.service.externalPort }} 
              readinessProbe:
                tcpSocket:
                  port: {{ .Values.service.internalPort }}
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5  
              livenessProbe:
                tcpSocket:
                  port: {{ .Values.service.internalPort }}
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5  
      volumes:
        - name: config-volume
          configMap:
            name: service-auth-dev01-app-config
          envFrom:
            - prefix: ""
              configMapRef:
               name: {{ template "service-auth.fullname" . }}
