apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-auth.fullname" . }}-app-config
  labels:
{{ include "service-auth.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-auth-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-auth-dev01
    db_pass: yb2zDGweLhzcTei
    db_name: service-auth-dev01
    rabbit_host: dove.rmq.cloudamqp.com/yttgqspx
    rabbit_port: 5672 
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    redis_host: redis-11742.c102.us-east-1-mz.ec2.cloud.redislabs.com
    redis_port: 11742
    redis_pass: eXSGf6RiDxRmORkzT1fJD5wspgDqgkwY
