apiVersion: v1
kind: ConfigMap
metadata:
  name: service-auth-dev01-app-config
  labels:
{{ include "service-auth.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-auth-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-auth-dev01
    db_pass: yb2zDGweLhzcTei
    db_name: service-auth-dev01
    rabbit_host: TBD
    rabbit_port: 5672
    rabbit_user: TBD
    rabbit_pass: TBD
    redis_host: TBD
    redis_port: 6379
