apiVersion: v1
kind: ConfigMap
metadata:
  name: service-auth-dev01-app-config
  labels:
{{ include "service-auth.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-auth-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-auth-dev01
    db_pass: yb2zDGweLhzcTei
    db_name: service-auth-dev01
    rabbit_host: tbd 
    rabbit_port: 132 
    rabbit_user: TBD
    rabbit_pass: TBD
    redis_host: redis-11742.c102.us-east-1-mz.ec2.cloud.redislabs.com
    redis_port: 11742
    redis_pass: eXSGf6RiDxRmORkzT1fJD5wspgDqgkwY
