apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-employee.fullname" . }}-app-config
  labels:
{{ include "service-employee.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-employee-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-employee-dev01
    db_pass: eR9sLUaZ6Hcow2D
    db_name: service-employee-dev01
    rabbit_host: dove.rmq.cloudamqp.com
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
