apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "service-customer.fullname" . }}
  labels:
{{ include "service-customer.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end}}
