apiVersion: v1
kind: Service
metadata:
  name: {{ template "service-customer.fullname" . }}
  labels:
{{ include "service-customer.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ template "service-customer.fullname" . }}
  selector:
{{ include "service-customer.selector" . | indent 4 }}
