apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-customer.fullname" . }}-app-config
  labels:
{{ include "service-customer.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-customer-dev01.yaml: |
    customer_list_enabled: true
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-customer-dev01
    db_pass: cbiEz4CRNmXj6st
    db_name: service-customer-dev01
    rabbit_host: dove.rmq.cloudamqp.com
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
