apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-merchant.fullname" . }}-app-config
  labels:
{{ include "service-merchant.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-merchant-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-merchant-dev01
    db_pass: yb2zDGweLhzcTei
    db_name: service-merchant-dev01
    rabbit_host: dove.rmq.cloudamqp.com/yttgqspx
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
