apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "dev01-base.fullname" . }}
  labels:
{{ include "dev01-base.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
