apiVersion: batch/v1
kind: Job
metadata:
  name: init-rabbit
spec:
  template:
    metadata:
      name: init-rabbit
    spec:
      restartPolicy: Never
      containers:
      - name: init-rabbit
        image: {{ .Values.toolkit }}
        command: ["bash"]
        args: ["-c", "./scripts/init-rabbit.sh"]
        env:
          - name: RABBIT_HOST
            value: {{ .Values.env.rabbit_host }}
          - name: RABBIT_VHOST
            value: {{ .Values.env.rabbit_vhost }}
          - name: RABBIT_PASSWORD
            value: {{ .Values.env.rabbit_pass }}
          - name: RABBIT_USER
            value: {{ .Values.env.rabbit_user }}
          - name: RABBIT_PORT
            value: {{ .Values.env.rabbit_ssl_port | quote }} 

