apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service-wallet.fullname" . }}-app-config
  labels:
{{ include "service-wallet.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
data:
  service-wallet-dev01.yaml: |
    db_host: 10.126.224.3
    db_port: 5432
    db_user: service-wallet-dev01
    db_pass: 8geXE9X7Fuu7YDw
    db_name: service-wallet-dev01
    rabbit_host: dove.rmq.cloudamqp.com/yttgqspx
    rabbit_port: 5672 
    rabbit_ssl_port: 443
    rabbit_user: yttgqspx
    rabbit_pass: BUQi0dpPilTtBcgUwHPQmktGkgZ29ExE
    rabbit_vhost: yttgqspx
